// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: MsgScheme.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace GameProtos
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public RequestMsg requestMsg
        {
            get { return __pbn__msg.Is(2) ? ((RequestMsg)__pbn__msg.Object) : default; }
            set { __pbn__msg = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializerequestMsg() => __pbn__msg.Is(2);
        public void ResetrequestMsg() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__msg, 2);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__msg;

        [global::ProtoBuf.ProtoMember(3)]
        public ResponseMsg responseMsg
        {
            get { return __pbn__msg.Is(3) ? ((ResponseMsg)__pbn__msg.Object) : default; }
            set { __pbn__msg = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeresponseMsg() => __pbn__msg.Is(3);
        public void ResetresponseMsg() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__msg, 3);

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            RequestMsg = 0,
            ResponseMsg = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Head head { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public LoginRequest loginRequest
        {
            get { return __pbn__body.Is(2) ? ((LoginRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeloginRequest() => __pbn__body.Is(2);
        public void ResetloginRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 2);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__body;

        [global::ProtoBuf.ProtoMember(3)]
        public FixAccountPasswordRequest fixAccountPasswordRequest
        {
            get { return __pbn__body.Is(3) ? ((FixAccountPasswordRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializefixAccountPasswordRequest() => __pbn__body.Is(3);
        public void ResetfixAccountPasswordRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 3);

        [global::ProtoBuf.ProtoMember(4)]
        public LogoutRequest logoutRequest
        {
            get { return __pbn__body.Is(4) ? ((LogoutRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializelogoutRequest() => __pbn__body.Is(4);
        public void ResetlogoutRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 4);

        [global::ProtoBuf.ProtoMember(5)]
        public BankBaseRequest bankBaseRequest
        {
            get { return __pbn__body.Is(5) ? ((BankBaseRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializebankBaseRequest() => __pbn__body.Is(5);
        public void ResetbankBaseRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 5);

        [global::ProtoBuf.ProtoMember(6)]
        public BankAllItemRequest bankItemRequest
        {
            get { return __pbn__body.Is(6) ? ((BankAllItemRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(6, value); }
        }
        public bool ShouldSerializebankItemRequest() => __pbn__body.Is(6);
        public void ResetbankItemRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 6);

        [global::ProtoBuf.ProtoMember(7)]
        public BankCustomItemRequest bankCustomItemRequest
        {
            get { return __pbn__body.Is(7) ? ((BankCustomItemRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(7, value); }
        }
        public bool ShouldSerializebankCustomItemRequest() => __pbn__body.Is(7);
        public void ResetbankCustomItemRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 7);

        [global::ProtoBuf.ProtoMember(8)]
        public CharactersGetRequest charactersGetRequest
        {
            get { return __pbn__body.Is(8) ? ((CharactersGetRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(8, value); }
        }
        public bool ShouldSerializecharactersGetRequest() => __pbn__body.Is(8);
        public void ResetcharactersGetRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 8);

        [global::ProtoBuf.ProtoMember(9)]
        public StartMainLevelBattleRequest startMainLevelBattleRequest
        {
            get { return __pbn__body.Is(9) ? ((StartMainLevelBattleRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(9, value); }
        }
        public bool ShouldSerializestartMainLevelBattleRequest() => __pbn__body.Is(9);
        public void ResetstartMainLevelBattleRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 9);

        [global::ProtoBuf.ProtoMember(10)]
        public StarUpRequest starUpRequest
        {
            get { return __pbn__body.Is(10) ? ((StarUpRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(10, value); }
        }
        public bool ShouldSerializestarUpRequest() => __pbn__body.Is(10);
        public void ResetstarUpRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 10);

        [global::ProtoBuf.ProtoMember(11)]
        public RuneRandRequest runeRandRequest
        {
            get { return __pbn__body.Is(11) ? ((RuneRandRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(11, value); }
        }
        public bool ShouldSerializeruneRandRequest() => __pbn__body.Is(11);
        public void ResetruneRandRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 11);

        [global::ProtoBuf.ProtoMember(12)]
        public RuneUpRequest runeUpRequest
        {
            get { return __pbn__body.Is(12) ? ((RuneUpRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(12, value); }
        }
        public bool ShouldSerializeruneUpRequest() => __pbn__body.Is(12);
        public void ResetruneUpRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 12);

        [global::ProtoBuf.ProtoMember(13)]
        public BreakUpCharacterRequest breakUpCharacterRequest
        {
            get { return __pbn__body.Is(13) ? ((BreakUpCharacterRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(13, value); }
        }
        public bool ShouldSerializebreakUpCharacterRequest() => __pbn__body.Is(13);
        public void ResetbreakUpCharacterRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 13);

        [global::ProtoBuf.ProtoMember(14)]
        public RebornRequest rebornRequest
        {
            get { return __pbn__body.Is(14) ? ((RebornRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(14, value); }
        }
        public bool ShouldSerializerebornRequest() => __pbn__body.Is(14);
        public void ResetrebornRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 14);

        [global::ProtoBuf.ProtoMember(15)]
        public LevelUpCharacterRequest levelUpCharacterRequest
        {
            get { return __pbn__body.Is(15) ? ((LevelUpCharacterRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(15, value); }
        }
        public bool ShouldSerializelevelUpCharacterRequest() => __pbn__body.Is(15);
        public void ResetlevelUpCharacterRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 15);

        [global::ProtoBuf.ProtoMember(16)]
        public ChangeTeamRequest changeTeamRequest
        {
            get { return __pbn__body.Is(16) ? ((ChangeTeamRequest)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(16, value); }
        }
        public bool ShouldSerializechangeTeamRequest() => __pbn__body.Is(16);
        public void ResetchangeTeamRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 16);

        [global::ProtoBuf.ProtoContract()]
        public enum Head
        {
            LoginRequest = 0,
            FixAccountPasswordRequest = 1,
            LogoutRequest = 2,
            BankBaseRequest = 3,
            BankItemAllRequest = 4,
            BankItemCustomRequest = 5,
            CharactersGetRequest = 6,
            StartMainLevelBattleRequest = 7,
            StarUpRequest = 8,
            RuneRandRequest = 9,
            RuneUpRequest = 10,
            BreakUpCharacterRequest = 11,
            RebornRequest = 12,
            LevelUpCharacterRequest = 13,
            ChangeTeamRequest = 14,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LevelUpCharacterRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint cId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RebornRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BreakUpCharacterRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int cId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RuneUpRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int cId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RuneRandRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint cId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarUpRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int cId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartMainLevelBattleRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeTeamRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"slot1")]
        public int Slot1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"slot2")]
        public int Slot2 { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"slot3")]
        public int Slot3 { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"slot4")]
        public int Slot4 { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"slot5")]
        public int Slot5 { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"slot6")]
        public int Slot6 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CharactersGetRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Head head { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ErrorResponse errorResponse
        {
            get { return __pbn__body.Is(2) ? ((ErrorResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeerrorResponse() => __pbn__body.Is(2);
        public void ReseterrorResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 2);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__body;

        [global::ProtoBuf.ProtoMember(3)]
        public LoginResponse loginResponse
        {
            get { return __pbn__body.Is(3) ? ((LoginResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeloginResponse() => __pbn__body.Is(3);
        public void ResetloginResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 3);

        [global::ProtoBuf.ProtoMember(4)]
        public FixAccountPasswordResponse fixAccountPasswordResponse
        {
            get { return __pbn__body.Is(4) ? ((FixAccountPasswordResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializefixAccountPasswordResponse() => __pbn__body.Is(4);
        public void ResetfixAccountPasswordResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 4);

        [global::ProtoBuf.ProtoMember(5)]
        public LogoutResponse logoutResponse
        {
            get { return __pbn__body.Is(5) ? ((LogoutResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializelogoutResponse() => __pbn__body.Is(5);
        public void ResetlogoutResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 5);

        [global::ProtoBuf.ProtoMember(6)]
        public BankBaseResponse bankBaseResponse
        {
            get { return __pbn__body.Is(6) ? ((BankBaseResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(6, value); }
        }
        public bool ShouldSerializebankBaseResponse() => __pbn__body.Is(6);
        public void ResetbankBaseResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 6);

        [global::ProtoBuf.ProtoMember(7)]
        public BankItemResponse bankItemResponse
        {
            get { return __pbn__body.Is(7) ? ((BankItemResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(7, value); }
        }
        public bool ShouldSerializebankItemResponse() => __pbn__body.Is(7);
        public void ResetbankItemResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 7);

        [global::ProtoBuf.ProtoMember(8)]
        public CharactersGetResponse charactersGetResponse
        {
            get { return __pbn__body.Is(8) ? ((CharactersGetResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(8, value); }
        }
        public bool ShouldSerializecharactersGetResponse() => __pbn__body.Is(8);
        public void ResetcharactersGetResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 8);

        [global::ProtoBuf.ProtoMember(9)]
        public LevelUpCharacterResponse levelUpCharacterResponse
        {
            get { return __pbn__body.Is(9) ? ((LevelUpCharacterResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(9, value); }
        }
        public bool ShouldSerializelevelUpCharacterResponse() => __pbn__body.Is(9);
        public void ResetlevelUpCharacterResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 9);

        [global::ProtoBuf.ProtoMember(10)]
        public RebornResponse rebornResponse
        {
            get { return __pbn__body.Is(10) ? ((RebornResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(10, value); }
        }
        public bool ShouldSerializerebornResponse() => __pbn__body.Is(10);
        public void ResetrebornResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 10);

        [global::ProtoBuf.ProtoMember(11)]
        public BreakUpCharacterResponse breakUpCharacterResponse
        {
            get { return __pbn__body.Is(11) ? ((BreakUpCharacterResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(11, value); }
        }
        public bool ShouldSerializebreakUpCharacterResponse() => __pbn__body.Is(11);
        public void ResetbreakUpCharacterResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 11);

        [global::ProtoBuf.ProtoMember(12)]
        public RuneUpResponse runeUpResponse
        {
            get { return __pbn__body.Is(12) ? ((RuneUpResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(12, value); }
        }
        public bool ShouldSerializeruneUpResponse() => __pbn__body.Is(12);
        public void ResetruneUpResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 12);

        [global::ProtoBuf.ProtoMember(13)]
        public RuneRandResponse runeRandResponse
        {
            get { return __pbn__body.Is(13) ? ((RuneRandResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(13, value); }
        }
        public bool ShouldSerializeruneRandResponse() => __pbn__body.Is(13);
        public void ResetruneRandResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 13);

        [global::ProtoBuf.ProtoMember(14)]
        public StarUpResponse starUpResponse
        {
            get { return __pbn__body.Is(14) ? ((StarUpResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(14, value); }
        }
        public bool ShouldSerializestarUpResponse() => __pbn__body.Is(14);
        public void ResetstarUpResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 14);

        [global::ProtoBuf.ProtoMember(15)]
        public StartMainLevelBattleResponse startMainLevelBattleResponse
        {
            get { return __pbn__body.Is(15) ? ((StartMainLevelBattleResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(15, value); }
        }
        public bool ShouldSerializestartMainLevelBattleResponse() => __pbn__body.Is(15);
        public void ResetstartMainLevelBattleResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 15);

        [global::ProtoBuf.ProtoMember(16)]
        public ChangeTeamResponse changeTeamResponse
        {
            get { return __pbn__body.Is(16) ? ((ChangeTeamResponse)__pbn__body.Object) : default; }
            set { __pbn__body = new global::ProtoBuf.DiscriminatedUnionObject(16, value); }
        }
        public bool ShouldSerializechangeTeamResponse() => __pbn__body.Is(16);
        public void ResetchangeTeamResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__body, 16);

        [global::ProtoBuf.ProtoContract()]
        public enum Head
        {
            ErrorResponse = 0,
            LoginResponse = 1,
            FixAccountPasswordResponse = 2,
            LogoutResponse = 3,
            BankBaseResponse = 4,
            BankItemResponse = 5,
            CharactersGetResponse = 6,
            LevelUpCharacterResponse = 7,
            RebornResponse = 8,
            BreakUpCharacterResponse = 9,
            RuneUpResponse = 10,
            RuneRandResponse = 11,
            StarUpResponse = 12,
            StartMainLevelBattleResponse = 13,
            ChangeTeamResponse = 14,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LevelUpCharacterResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ok")]
        public bool Ok { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RebornResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ok")]
        public bool Ok { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BreakUpCharacterResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ok")]
        public bool Ok { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RuneUpResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ok")]
        public bool Ok { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RuneRandResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ok")]
        public bool Ok { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarUpResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ok")]
        public bool Ok { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartMainLevelBattleResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pass")]
        public bool Pass { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeTeamResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pass")]
        public bool Pass { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CharacterStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int Star { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool InBattle { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int RuneType { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int RuneLevel { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int BreakTimes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CharactersGetResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"characters")]
        public global::System.Collections.Generic.List<Character> Characters { get; set; } = new global::System.Collections.Generic.List<Character>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Character : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public int Id { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public CharacterStatus characterStatus { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BankCustomItemRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"itemId", IsPacked = true)]
        public int[] itemIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BankAllItemRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BankBaseRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BankBaseResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Money> Moneys { get; set; } = new global::System.Collections.Generic.List<Money>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Money : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int itemId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"num")]
        public ulong Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BankItemResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Item> Items { get; set; } = new global::System.Collections.Generic.List<Item>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Item : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int itemId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"num")]
        public uint Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LogoutResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LogoutRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FixAccountPasswordRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string accountId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string oldPassword { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string newPassword { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FixAccountPasswordResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Reason reason { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Reason
        {
            [global::ProtoBuf.ProtoEnum(Name = @"OK")]
            Ok = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"NO_GOOD_ACCOUNT_ID")]
            NoGoodAccountId = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"NO_GOOD_PASSWORD")]
            NoGoodPassword = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_NOT_EXIST")]
            AccountNotExist = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"WRONG_PASSWORD")]
            WrongPassword = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"OTHER")]
            Other = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string accountId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"password")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Password { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Reason reason { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public CharactersGetResponse charactersGetResponse { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public BankBaseResponse bankBaseResponse { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Reason
        {
            [global::ProtoBuf.ProtoEnum(Name = @"OK")]
            Ok = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"NO_GOOD_ACCOUNT")]
            NoGoodAccount = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"NO_GOOD_PASSWORD")]
            NoGoodPassword = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"WRONG_PASSWORD")]
            WrongPassword = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"NOT_EXIST_SO_CREATE")]
            NotExistSoCreate = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"OTHER")]
            Other = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ErrorResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrorType errorType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public enum ErrorType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
            Unknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"OTHER_LOGIN")]
            OtherLogin = 1,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
